# Generated by Django 4.2.19 on 2025-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user_rating_user_ratinganswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, help_text='Фото которое будет отобрадажаться на обложке объявления', upload_to='media/main_covers', verbose_name='Главное фото'),
            preserve_default=False,
        ),
    ]
