# Generated by Django 4.2.19 on 2025-03-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinganswer',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_answers', to='main.rating', verbose_name='Отзыв'),
        ),
    ]
