# Generated by Django 4.2.19 on 2025-03-15 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='PaymentRequest',
        ),
    ]
