# Generated by Django 4.2.19 on 2025-03-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_paymentrequest_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма'),
            preserve_default=False,
        ),
    ]
