# Generated by Django 4.2.19 on 2025-03-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_is_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_otp',
            field=models.BooleanField(default=False, help_text='Если включить, то на этот акк будет работать Двухфакторка'),
        ),
    ]
